# Generated by Django 4.0.4 on 2022-04-25 04:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Company_Name', models.CharField(max_length=100)),
                ('Email_ID', models.EmailField(max_length=254)),
                ('Company_Code', models.CharField(max_length=100, unique=True)),
                ('Strength', models.IntegerField()),
                ('Web_site', models.CharField(max_length=100)),
                ('Created_time', models.DateTimeField(unique=True)),
            ],
        ),
    ]
