# Generated by Django 4.0.4 on 2022-04-25 06:09

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='Company_Code',
            field=models.CharField(max_length=100, unique=True, validators=[django.core.validators.RegexValidator('^[a-zA-Z]{2}*[0-9]{2}*[E-N]{1}*$')]),
        ),
    ]
