# Generated by Django 4.0.4 on 2022-04-25 07:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_alter_company_company_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='Company_Code',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
